# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache:
    pip: true

matrix:
    include:
        - python: '3.6'
#        - python: '3.7'
#        - python: '3.7-dev'
#        - python: '3.8-dev'
#    allow_failures:
#        - python: '3.7-dev'
#        - python: '3.8-dev'

branches:
    only:
        - master

install:
    - python setup.py develop
    - pip install -r requirements_dev.txt

script:
    - pre-commit run --all-files
